#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width        1
bspc config window_gap          10

bspc config top_padding 35
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner

#bspc config click_to_focus	 true
#bspc config focused_border_color "#ffffff"
#bspc config normal_border_color "#000000"
#bspc config normal_border_color "#00000000"
#bspc config active_border_color "#c80000"
#bspc config focused_border_color "#00c80f" 
#bspc config presel_border_color "#9a875f"
#bspc config urgent_border_color "#9f7155"
#bspc config focused_locked_border_color "#9a875f"

bspc rule -a Docky layer=above manage=on border=off
