#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width        1
bspc config window_gap          10

bspc config top_padding 35
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc rule -a Docky layer=above manage=on border=off
